# Generated by Django 4.2.4 on 2023-08-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='entree_rating',
            field=models.IntegerField(default=100),
        ),
    ]
