# Generated by Django 4.2.4 on 2023-08-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_meal_entree_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='eaten_by',
        ),
    ]
