# Generated by Django 4.2.4 on 2023-08-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_meal_eaten_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='notes',
            field=models.CharField(default='', max_length=500),
        ),
    ]
