# Generated by Django 4.2.4 on 2023-08-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_meal_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
