# Generated by Django 4.2.4 on 2023-08-14 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meals', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='eaten_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date dined'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='entree_choice_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='restaurant_name_text',
            field=models.CharField(max_length=100),
        ),
    ]
