# Generated by Django 4.2.4 on 2023-09-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_meal_eaten_by_alter_meal_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='entree_choice_text',
            new_name='entree_choice',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='restaurant_name_text',
            new_name='restaurant_name',
        ),
    ]
